services:

  # SOURCE
  # INGESTION
  nifi:
      image: apache/nifi:${NIFI_VERSION}
      container_name: nifi-otmzsp
      hostname: nifi-otmzsp
      networks:
      - otmzsp_network
      volumes:
        - ./volumes/nifi/util:/util
        - ./volumes/nifi/database_repository:/opt/nifi/nifi-current/database_repository
        - ./volumes/nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
        - ./volumes/nifi/content_repository:/opt/nifi/nifi-current/content_repository
        - ./volumes/nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
        - ./volumes/nifi/state:/opt/nifi/nifi-current/state
        - ./volumes/nifi/conf:/opt/nifi/nifi-current/conf
        - ./volumes/nifi/logs:/opt/nifi/nifi-current/logs
        - ./volumes/nifi/util/jar:/util/jar

      environment:
        NIFI_WEB_HTTP_PORT: "9090"
        NIFI_WEB_HTTPS_HOST: "nifi"
        TZ: "America/Sao_Paulo"
      command: >
        sh -c "ln -snf /usr/share/zoneinfo/$$TZ /etc/localtime && echo $$TZ > /etc/timezone"
      
      ports:
        - 49090:9090
      deploy:
        resources:
          limits:
            memory: 2g
            #cpus: '0.2'

  #DATA LAKE
  minio-otmzsp:
    image: minio/minio:${MINIO_VERSION}
    container_name: minio-otmzsp
    networks:
          - otmzsp_network
    entrypoint: sh
    command:   '-c ''mkdir -p /minio_data/raw && mkdir -p /minio_data/trusted && minio server /minio_data --console-address ":9001"'''
    ports:
      - "49000:9000"
      - "49001:9001"
    hostname: minio-otmzsp
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./volumes/minio/data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  otmzsp_network:
    name: otmzsp-network
    driver: bridge

